[package]
name = "ebg"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/eholk/ebg"
description = "Eric's Blog Generator, a simple static site generator inspired by Octopress."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-walkdir = "0.2.0"
bumpalo = "3.14.0"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.11", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6.8"
futures = "0.3.29"
futures-concurrency = "7.4.3"
hyper = { version = "0.14.27", features = ["http1", "server", "tcp"] }
indicatif = "0.17.7"
notify = "6.1.1"
pathdiff = "0.2.1"
pulldown-cmark = "0.9.3"
quick-xml = "0.31.0"
serde = { version = "1.0.168", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.22"
slug = "0.1.5"
syntect = "5.1.0"
tera = "1.19.1"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = [
    "fs",
    "io-util",
    "macros",
    "rt",
    "rt-multi-thread",
] }
tokio-stream = { version = "0.1.14", features = ["fs"] }
toml = "0.8.8"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["ansi", "env-filter"] }
