[package]
name = "ebg"
version = "0.2.0-dev"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/eholk/ebg"
description = "Eric's Blog Generator, a simple static site generator inspired by Octopress."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = [
    "fs",
    "io-util",
    "macros",
    "rt",
    "rt-multi-thread",
] }
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.1.4", features = ["derive"] }
eyre = "0.6.8"
futures = "0.3.26"
pulldown-cmark = "0.9.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
tokio-stream = { version = "0.1.11", features = ["fs"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["ansi", "env-filter"] }
tera = "1.17.1"
serde_json = "1.0.93"
async-walkdir = "0.2.0"
futures-concurrency = "7.1.0"
pathdiff = "0.2.1"
quick-xml = "0.27.1"
toml = "0.7.2"
syntect = "5.0.0"
thiserror = "1.0.38"
hyper = { version = "0.14.24", features = ["http1", "server", "tcp"] }
notify = "5.1.0"
bumpalo = "3.12.0"
slug = "0.1.4"
indicatif = "0.17.3"
