[package]
name = "ebg"
version = "0.2.2-dev"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/eholk/ebg"
description = "Eric's Blog Generator, a simple static site generator inspired by Octopress."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.1", features = [
    "fs",
    "io-util",
    "macros",
    "rt",
    "rt-multi-thread",
] }
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.11", features = ["derive"] }
eyre = "0.6.8"
futures = "0.3.28"
pulldown-cmark = "0.9.3"
serde = { version = "1.0.166", features = ["derive"] }
serde_yaml = "0.9.22"
tokio-stream = { version = "0.1.14", features = ["fs"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["ansi", "env-filter"] }
tera = "1.19.0"
serde_json = "1.0.100"
async-walkdir = "0.2.0"
futures-concurrency = "7.3.0"
pathdiff = "0.2.1"
quick-xml = "0.29.0"
toml = "0.7.6"
syntect = "5.0.0"
thiserror = "1.0.41"
hyper = { version = "0.14.27", features = ["http1", "server", "tcp"] }
notify = "6.0.1"
bumpalo = "3.13.0"
slug = "0.1.4"
indicatif = "0.17.5"
color-eyre = "0.6.2"
